// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// De[FirebaseOptions]

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT1O7N4-llUlNScrsFRsMm5mhh8gNQOdw',
    appId: '1:847720395126:web:fa5af1ffd83f66c3c80a57',
    messagingSenderId: '847720395126',
    projectId: 'zartekmenuapp',
    authDomain: 'zartekmenuapp.firebaseapp.com',
    storageBucket: 'zartekmenuapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTISen0MUQsJgNO614dHGR9XlQSBcqCWs',
    appId: '1:847720395126:android:04d33e2f8a675db5c80a57',
    messagingSenderId: '847720395126',
    projectId: 'zartekmenuapp',
    storageBucket: 'zartekmenuapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6-fOoCGWEDd751zzj-UI4ZKE2OOcx0Y',
    appId: '1:847720395126:ios:29d92cbbfe9aca05c80a57',
    messagingSenderId: '847720395126',
    projectId: 'zartekmenuapp',
    storageBucket: 'zartekmenuapp.appspot.com',
    iosBundleId: 'com.example.zartekProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI6-fOoCGWEDd751zzj-UI4ZKE2OOcx0Y',
    appId: '1:847720395126:ios:08581b6c9eddd63dc80a57',
    messagingSenderId: '847720395126',
    projectId: 'zartekmenuapp',
    storageBucket: 'zartekmenuapp.appspot.com',
    iosBundleId: 'com.example.zartekProject.RunnerTests',
  );
}
